export const INIT_PROBLEMS = 'INIT_PROBLEMS';
export const CREATE_PROBLEM = 'CREATE_PROBLEM';
export const DELETE_PROBLEM = 'DELETE_PROBLEM';
export const UPDATE_PROBLEM = 'UPDATE_PROBLEM';
export const CREATE_FAIL = 'CREATE_FAIL';

export const FETCH_COURSES = 'FETCH_COURSES';
export const CREATE_COURSE = 'CREATE_COURSE';

export const INIT_WELCOME = 'INIT_WELCOME';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FAIL = 'AUTH_FAIL';
